### ISSUE TITLE
How do we get it pulled into HA?

### ISSUE THREAD

**Issue by aechelon** [uvjustin/pyalarmdotcomajax#1]
@uvjustin I just tested it out and everything works great!
How do we get it pulled into HA?

**Comment by aechelon** [comment]
BTW, I also pointed [this thread](https://community.home-assistant.io/t/alarm-com-list-index-out-of-range/170670/45) to this version.

**Comment by uvjustin** [comment]
The PR for HA is at https://github.com/home-assistant/core/pull/32939

**Comment by aechelon** [comment]
Cool.  Thanks!

**Comment by uvjustin** [comment]
@aechelon

**Comment by uvjustin** [comment]
@aechelon Looks like they don't want any webscraping in HA going forward...we'll have to make this a custom component.

**Comment by uvjustin** [comment]
@aechelon I put the custom component here https://github.com/uvjustin/alarmdotcomajax

**Comment by aechelon** [comment]
@uvjustin Great.  Thank you!
