### ISSUE TITLE
Publish as a custom integration

### ISSUE THREAD

**Issue by akinomeroglu** [uvjustin/pyalarmdotcomajax#2]
Hello @uvjustin thanks for your and aechelon work. Unfortunately, HA is trying to avoid scrapping as a official integration because of their arch. decision. 

Could you kindly provide your package and official integration as a custom integration.

Thanks for your all help.

**Comment by uvjustin** [comment]
@akinomeroglu I put the custom component here https://github.com/uvjustin/alarmdotcomajax
