### ISSUE TITLE
Silent arming

### ISSUE THREAD

**Issue by aechelon** [uvjustin/pyalarmdotcomajax#3]
There's a [request on the HA forum](https://community.home-assistant.io/t/alarm-com-list-index-out-of-range/170670/62) to add silent arming to the arming parameters.

Referencing the node implementation [here](https://github.com/mkormendy/node-alarm-dot-com/blob/45ee5a2ef33f2d9d8cf152dca14f2977eedd2cd2/index.js) (line 282) it looks like that would involve adding parameter **silentArming** to the post.  See attached version.
[pyalarmdotcomajax.zip](https://github.com/uvjustin/pyalarmdotcomajax/files/4363470/pyalarmdotcomajax.zip)

**Comment by uvjustin** [comment]
Added the option...give it a try.
