### ISSUE TITLE
Silent Arming not working

### ISSUE THREAD

**Issue by aechelon** [uvjustin/pyalarmdotcomajax#5]
Hi Justin,
I've been testing the silentArming parameter and it doesn't seem to be working.
So far I have confirmed that the [web api example](https://github.com/schwark/pyalarmcom/blob/678631c3dbd2c48720961a9678718a5a67cc6d40/alarm.py3) works as expected and that the the json looks correct.

Here's what I see from the web api example:
{"forceBypass":false,"noEntryDelay":false,"silentArming":true,"statePollOnly":false}

Any ideas?

**Comment by uvjustin** [comment]
Hmm..It's hard for me to troubleshoot because my ADC system is not local so I can't tell if the silentArming function works or not. Does the system still arm but not silently? I actually do not have the silentArming option in my web interface so I can't compare the call to that, but compared to the other library that works, the call we make here looks almost exactly the same (minor difference in spacing and header). Also, the silentArming option is treated the same as the other options, so if they work I can't figure out why silentArming wouldn't work.

**Comment by aechelon** [comment]
Correct, it arms but there's a voice prompt.  

I added the silentArming option as an HA configuration flag (so it's either always on or always off), but I've been testing by hard-coding the value on line 240 of pyalarmdotcomajax.py.  

I haven't actually tested the other options yet.  The only other one that I see matches the UI on the native ADC iphone app is noEntryDelay.  I'll see if I can give that a try tomorrow.

One other item, someone on the HA forum asked if the custom component can be added to HACS.  I think that's a good idea.
Thoughts?

**Comment by aechelon** [comment]
I think I figured it out... The ajax header is missing Content-Type.

        self._ajax_headers = {
            "Accept": "application/vnd.api+json",
            "ajaxrequestuniquekey": None,
            **"Content-Type": "application/json; charset=UTF-8"**
        }

**Comment by uvjustin** [comment]
So that fixes it?
Strange why it would only require that for silentArming and not the other options...

**Comment by aechelon** [comment]
Nevermind, false alarm.  The parameter wasn't getting passed from HA properly.  When I tested hard-coding the silentarming value I was saving the file to the wrong place.  
Sorry man!

Any thoughts about putting the component in HACS?

**Comment by uvjustin** [comment]
Oh ok, makes sense. So does it work now? BTW, the current version of the alarmdotcomajax component has an optional argument for the silent arming setting.
I saw that someone opened an issue on HACS in the alarmdotcomajax repo but they closed it. I haven't used HACS before so need to familiarize myself with it. I'll try to put in on there in the next day or two.

**Comment by aechelon** [comment]
Not quite working yet.  I see the parameter coming through to the class and self._silentarming is initialized to True, but then in async_alarm_arm_home this turns it to False:

silentarming = self._silentarming in ["stay", "true"]

**Comment by uvjustin** [comment]
It doesn't take a boolean True/False, it takes a string "true" or "false". That's what the alarmdotcomajax library takes in from the config and that's what it passes to the python library.
The reason that code is there is because of this request https://github.com/uvjustin/alarmdotcomajax/issues/2
Use the latest version of the alarmdotcomajax code and see if that works for you.

**Comment by aechelon** [comment]
Gotcha!  I got thrown off because they're initialized as booleans:

    def __init__(
        self,
        username,
        password,
        websession,
        forcebypass=False,
        noentrydelay=False,
        silentarming=False,
    ):

        self._forcebypass = forcebypass  # "stay","away","true","false"
        self._noentrydelay = noentrydelay  # "stay","away","true","false"
        self._silentarming = silentarming  # "stay","away","true","false"

**Comment by aechelon** [comment]
Are you using it with alarm_control_panel.py?
If so, which version are you using with it?

After reading that request I also understand why home was changed to stay!

**Comment by uvjustin** [comment]
Oh sorry about that. Let me remove the defaults since we don't use them from the HA component anyway.
I just use the component installed as outlined in the README here: https://github.com/uvjustin/alarmdotcomajax

**Comment by aechelon** [comment]
Got it!  Just updated to the latest and everything is working great.

One other minor one that threw me off is that the example configuration.yaml in the README passed the values without quotes and I hadn't read all the way through to the part where you described all the accepted values :-/
